# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5792759c8690f570ed8be047a5779360e373a250b2693895e6153061741267e4ecc54e5361f27cf76975874d1a4c44c959d48f7e0d74e388187303235608005c

test:
  secret_key_base: 3afc62f931891182884b3a46aa0dca2d67a69bb3b967616993ffa6683265a757c8ca596413a02df03199363699193a89ac541533c85988b4b85ef56f73c21183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
